config/routes.rb
Rails.application.routes.draw do
  concern :versioned do
    resources :versions, except: %i[new create edit update destroy]
  end

  root to: 'paths#sitepath', via: :get, url: '/'

  # USERS
  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create'
  get 'account/confirm/:confirmation_code' => 'users#confirm', as: :confirm_account
  resource :account, controller: 'users', except: %i[index new create destroy]
  get 'profile/:id' => 'users#profile', as: :profile
  # SESSIONS
  get 'signin' => 'sessions#new', as: :signin
  post 'signin' => 'sessions#create'
  get 'signout' => 'sessions#delete', as: :signout
  delete 'signout' => 'sessions#destroy'
  # OAUTH
  match 'auth/:provider/callback' => 'sessions#oauth_callback', via: %i[get post]
  # AUTHORITIES
  resources :authorities
  # SETTINGS
  resources :settings do
    collection { get 'initialize_defaults' }
  end

  # CONTENT
  resources :paths
  resources :pages, concerns: :versioned
  resources :documents
  get 'download/:id/*filename' => 'documents#download', as: :download
  resources :events, concerns: :versioned do
    member do
      get 'approve'
      post 'approve' => 'events#set_approved'
      get 'merge'
      post 'merge' => 'events#perform_merge'
      post 'update_tags'
    end
    resources :external_links
  end
  resources :images
  resources :sources do
    member do
      get 'processor'
      post 'processor' => 'sources#runprocessor'
    end
  end
  get 'tags' => 'tags#index'
  get 'tags/:tag' => 'tags#tag'

  # PROJECTS
  resources :projects
  get 'project/*projecturl' => 'projects#show', as: :project_name, format: false

  # Calendar
  month_regexp = /0[1-9]|1[0-2]/
  year_regexp = /\d{4}/
  get 'calendar' => 'calendar#index', as: :calendar
  get 'calendar/subscribe' => 'calendar#subscribe', as: :calendar_subscribe
  get 'calendar/:year/:month/:day' => 'calendar#day', as: :calendar_day,
      constraints: { year: year_regexp, month: month_regexp, day: /0[1-9]|[1-3]\d/ }
  get 'calendar/:year/:month' => 'calendar#month', as: :calendar_month,
      constraints: { year: year_regexp, month: month_regexp }
  get 'calendar/:year' => 'calendar#year', as: :calendar_year,
      constraints: { year: year_regexp }

  get '*url' => 'paths#sitepath', format: false
end

app/models/event.rb
require 'active_record'
require 'authority_controlled'
require 'tag_list'
require 'user'
require 'text_cleaner'
require 'url_cleaner'
require 'import/ical_importer'

# Details of a calendar event
class Event < ApplicationRecord
  acts_as_authority_controlled authority_area: 'Calendar', item_authority_flag_field: :always_viewable
  # editor and edit_comment are used for Version records
  # is_sourcing is set when generating or updating from a Source (and SourcedItem)
  attr_accessor :editor, :edit_comment, :is_sourcing

  belongs_to :user
  belongs_to :image
  has_many :external_links, as: :item
  accepts_nested_attributes_for(
    :external_links,
    reject_if: ->(el) { el[:url].blank? }, allow_destroy: true
  )
  has_many :sourced_items, as: :item
  has_many :tags, as: :item, dependent: :delete_all
  has_many :versions, as: :item, dependent: :delete_all

  validates :title, length: { within: 1..255 }
  validates :start_at, presence: true
  validates :organizer, length: { within: 0..255, allow_blank: true }
  validates :organizer_url, length: { within: 0..255, allow_blank: true }
  validates :location, length: { within: 0..255, allow_blank: true }
  validates :address, length: { within: 0..255, allow_blank: true }
  validates :city, length: { within: 0..255, allow_blank: true }
  validates :province, length: { within: 0..31, allow_blank: true }
  validates :country, length: { within: 0..2, allow_blank: true }
  validates :location_url, length: { within: 0..255, allow_blank: true }
  validates :description, length: { within: 0..511, allow_blank: true }
  validates :content, length: { within: 0..8191, allow_blank: true }
  validate(
    :validate_end_at_not_before_start_at,
    :validate_timezone,
    :validate_not_both_is_draft_and_is_approved
  )

  default_scope { order('start_at') }
  scope :approved, -> { where(is_approved: true) }
  scope :upcoming, lambda { # use a lambda so the time is reloaded each time upcoming is called
    where(
      'start_at >= :day_start OR (end_at IS NOT NULL AND end_at >= :day_start)',
      day_start: Time.current.beginning_of_day
    )
  }
  scope :past, lambda { # use a lambda so the time is reloaded each time upcoming is called
    where(
      'start_at < :day_start AND (end_at IS NULL OR end_at < :day_start)',
      day_start: Time.current.beginning_of_day
    )
  }
  scope :falls_between_dates, lambda { |start_date, end_date|
    start_time = Time.zone.local(start_date.year, start_date.month, start_date.day, 0, 0, 0)
    end_time = Time.zone.local(end_date.year, end_date.month, end_date.day, 0, 0, 0) + 1.day
    where(
      # matches if event#start_at falls within the given dates
      '(start_at >= :start_time AND start_at < :end_time)' +
      # matches if event#end_at is set and falls within the given dates
      ' OR (end_at IS NOT NULL AND end_at > :start_time AND end_at < :end_time)' +
      # matches if event#start_at is before the dates and event#end_at is after the dates
      ' OR (end_at IS NOT NULL AND start_at < :start_time AND end_at >= :end_time)',
      start_time: start_time, end_time: end_time
    )
  }
  scope :falls_on_date, lambda { |the_date|
    start_time = Time.zone.local(the_date.year, the_date.month, the_date.day, 0, 0, 0)
    end_time = start_time + 1.day
    where(
      '(start_at >= :start_time AND start_at < :end_time)' \
      ' OR ' \
      '(end_at IS NOT NULL AND start_at < :end_time AND end_at >= :start_time)',
      start_time: start_time, end_time: end_time
    )
  }
  scope :tagged, lambda { |tag|
    tag = Tag.new.taggify_text(tag)
    joins(:tags).where(tags: { tag: tag })
  }

  before_create :set_timezone
  before_save :approve_if_authority
  after_update :flag_as_modified_for_sourcing
  after_save :add_version
  after_save :save_tag_list
  before_destroy :ignore_sourced_items_on_destroy

  def initialize(*args)
    super(*args)
    # if city, province and country are all blank
    if country.blank? && province.blank? && city.blank?
      # use defaults
      self.city ||= Wayground::Application::DEFAULT_CITY
      self.province ||= Wayground::Application::DEFAULT_PROVINCE
      self.country ||= Wayground::Application::DEFAULT_COUNTRY
    end
  end

  # VALIDATION METHODS

  # An event cannot end before it begins.
  def validate_end_at_not_before_start_at
    have_both_dates = start_at.present? && end_at.present?
    end_before_start = have_both_dates && start_at.to_datetime > end_at.to_datetime
    errors.add(:end_at, 'must be after the start date and time') if end_before_start
  end

  # An event cannot be both a draft and approved at the same time.
  def validate_not_both_is_draft_and_is_approved
    errors.add(:is_approved, 'cannot approve an event when it is still a draft') if is_draft && is_approved
  end

  # If the timezone is set for an event, it must be valid
  def validate_timezone
    timezone_invalid = timezone.present? && !(ActiveSupport::TimeZone[timezone])
    errors.add(:timezone, 'must be a recognized timezone name') if timezone_invalid
  end

  # BEFORE/AFTER CALLBACKS

  # Attempts to set the timezone based on the user’s timezone,
  # falling back to the default timezone.
  # Called before save on create.
  def set_timezone
    if timezone.blank?
      self.timezone =
        if user.present? && user.timezone?
          user.timezone
        else
          Time.zone_default.name
        end
    end
  end

  # Called before save.
  def approve_if_authority
    self.is_approved = true if !is_approved && user && user.authority_for_area('Calendar', :can_approve)
  end

  # Called after save on update.
  def flag_as_modified_for_sourcing
    unless is_sourcing
      sourced_items.each { |sourced_item| sourced_item.update(has_local_modifications: true) }
    end
  end

  # Add a Version based on the current state of this item.
  # Called after save.
  def add_version
    previous_version = versions.last
    version = new_version
    if previous_version
      diff = previous_version.diff_with(version)
      unless diff.size.positive?
        version.destroy
        return
      end
    end
    version.save!
  end

  # set the sourced_items to ignore when destroying this event
  def ignore_sourced_items_on_destroy
    sourced_items.update_all(
      is_ignored: true, item_type: nil, item_id: nil
    )
  end

  # VERSIONS

  def new_version
    versions.build(
      user: editor, edited_at: updated_at, edit_comment: edit_comment,
      title: title, values: values_for_version
    )
  end

  def values_for_version
    {
      timezone: timezone,
      is_allday: is_allday,
      is_draft: is_draft,
      is_approved: is_approved,
      is_wheelchair_accessible: is_wheelchair_accessible,
      is_adults_only: is_adults_only,
      is_tentative: is_tentative,
      is_cancelled: is_cancelled,
      is_featured: is_featured,
      organizer: organizer,
      organizer_url: organizer_url,
      location: location,
      address: address,
      city: city,
      province: province,
      country: country,
      location_url: location_url,
      content: content,
      description: description,
      tag_list: tag_list.to_s,
      start_at: start_at,
      end_at: end_at
    }
  end

  # Setters
  # pre-flight cleaners for attributes passed in

  def title=(title_str)
    self[:title] = TextCleaner.clean(title_str)
  end

  def description=(description_str)
    self[:description] = TextCleaner.clean(description_str)
  end

  def content=(content_str)
    self[:content] = TextCleaner.clean(content_str)
  end

  def organizer=(organizer_str)
    self[:organizer] = TextCleaner.clean(organizer_str)
  end

  def organizer_url=(organizer_url_str)
    self[:organizer_url] = UrlCleaner.clean(organizer_url_str)
  end

  def location=(location_str)
    self[:location] = TextCleaner.clean(location_str)
  end

  def address=(address_str)
    self[:address] = TextCleaner.clean(address_str)
  end

  def city=(city_str)
    self[:city] = TextCleaner.clean(city_str)
  end

  def province=(province_str)
    self[:province] = TextCleaner.clean(province_str)
  end

  def location_url=(location_url_str)
    self[:location_url] = UrlCleaner.clean(location_url_str)
  end

  def tag_list
    @tag_list ||= Wayground::TagList.new(tags: tags, editor: editor)
  end

  # Take a comma-separated string of tag titles,
  # add any tags that don’t already exist for the event,
  # update any changed titles of tags that do exist,
  # remove existing tags that are not in the supplied list.
  def tag_list=(value)
    @tag_list = nil
    tag_list.tags = value
  end

  def save_tag_list
    tag_list.save!
  end

  # VALUES

  # return the earliest date that an event occurs on
  def self.earliest_date
    event = first
    event.start_at.to_date if event
  end

  # return the last date that an event occurs on
  def self.last_date
    # TODO: potentially take into account the last end_date if it is > the last start_date
    event = last
    event.start_at.to_date if event
  end

  def multi_day?
    end_at? && start_at.to_date != end_at.to_date
  end

  # APPROVAL

  # If the event is not already approved,
  # and the given user has authority to approve events,
  # set the is_approved flag
  # (without triggering any sourced_items to be flagged as locally modified).
  def approve_by(user)
    if is_approved?
      true
    elsif user && user.authority_for_area('Calendar', :can_approve)
      # approvals should not affect sourced_items’ locally modified status
      self.is_sourcing = !changed?
      # parameters for the version record to be associated with this approval
      self.editor = user
      self.edit_comment = "Approved by #{user.name}"
      # approve it
      self.is_approved = true
      success = save
      # cleanup
      self.is_sourcing = false
      success # did the record successfully update?
    else
      false
    end
  end

  # iCalendar SOURCE/IMPORT PROCESSING

app/controllers/events_controller.rb
require 'event/day_events'
require 'event/event_selector'
require 'merger'

# Access events.
class EventsController < ApplicationController
  before_action :set_user
  before_action :set_event, except: %i[index new create]
  before_action :requires_login, only: %i[new create]
  before_action :requires_update_authority, only: %i[edit update merge perform_merge]
  before_action :requires_delete_authority, only: %i[delete destroy merge perform_merge]
  before_action :requires_approve_authority, only: %i[approve set_approved]
  before_action :set_section
  before_action :set_new_event, only: %i[new create]
  before_action :set_editor, only: %i[create update destroy approve merge perform_merge]

  def index
    selector = Wayground::Event::EventSelector.new(
      range: params[:range] || params[:r], tag: params[:tag], user: @user
    )
    @events = selector.events
    @range = selector.range
    @tag = selector.tag
    page_metadata(title: selector.title)
  end

  def show
    page_metadata(
      title: "#{@event.start_at.to_s(:simple_date)}: #{@event.title}", description: @event.description
    )
    if !@event.is_approved?
      page_metadata.nocache = true
      message = 'This event listing has not been approved by a moderator yet.'
    elsif @event.is_cancelled
      message = 'This event has been cancelled.'
    elsif @event.is_tentative
      message = 'This event is tentative.'
    end
    flash.now.alert = message if message
  end

  def new; end

  def create
    @event.user = @user
    if @event.save
      notice =
        if @user.present? && @user.authority_for_area('Calendar', :is_owner)
          'The event has been saved.'
        else
          'The event has been submitted.'
        end
      redirect_to(@event, notice: notice)
    else
      render action: 'new'
    end
  end

  def edit
    page_metadata(title: "Edit Event: #{@event.title}")
  end

  def update
    page_metadata(title: "Edit Event: #{@event.title}")
    if @event.update(event_params)
      notice = 'The event has been saved.'
      redirect_to(@event, notice: notice)
    else
      render action: 'edit'
    end
  end

  def update_tags
    @event.tag_list = params[:tag_list]
    @event.editor = @user
    @event.edit_comment = 'Updated tag list.'
    # updating tags should not affect sourced_items’ locally modified status
    @event.is_sourcing = true
    if @event.save
      redirect_to(@event, notice: 'The event tags have been saved.')
    else
      redirect_to(@event, alert: 'Unable to save the changes to the tags!')
    end
  end

  def delete
    page_metadata(title: "Delete Event: #{@event.title}")
  end

  def destroy
    @event.destroy
    redirect_to(events_url)
  end

  def approve
    if @event.is_approved?
      redirect_to(@event, notice: 'The event has already been approved.')
    else
      page_metadata(title: "Approve Event: #{@event.title}")
    end
  end

  def set_approved
    if @event.approve_by(@user)
      redirect_to(@event, notice: 'The event is now approved.')
    else
      redirect_to(@event, alert: 'Failed to approve the event!')
    end
  end

  def merge
    page_metadata(title: "Merge Event: #{@event.title}")
    @day_events = Wayground::Event::DayEvents.new(
      events: Event.falls_on_date(@event.start_at).where('id != ?', @event.id)
    )
  end

  def perform_merge
    page_metadata(title: "Merge Event: #{@event.title}")
    @merge_with = Event.find(params[:merge_with])
    @merge_with.editor = @user
    merger = Merger::EventMerger.new(@event)
    @conflicts = merger.merge_into!(@merge_with)
  end

  protected

  # The actions for this controller, other than viewing, require login and usually authorization.
  def requires_login
    raise Wayground::LoginRequired unless @user
  end

  def requires_authority(action)
    event_allowed = @event && @event.authority_for_user_to?(@user, action)
    can_do = event_allowed || (@user && @user.authority_for_area(Event.authority_area, action))
    raise Wayground::AccessDenied unless can_do
  end

  def requires_update_authority
    requires_authority(:can_update)
  end

  def requires_delete_authority
    requires_authority(:can_delete)
  end

  def requires_approve_authority
    requires_authority(:can_approve)
  end

  def set_section
    @site_section = :events
  end

  def set_user
    @user = current_user
  end

  # Most of the actions for this controller receive the id of an Event as a parameter.
  def set_event
    @event = Event.find(params[:id])
  end

  def set_new_event
    page_metadata(title: 'New Event')
    @event = Event.new(event_params)
  end

  def set_editor
    @event.editor = @user
  end

  def event_params
    params.fetch(:event, {}).permit(
      :start_at, :end_at, :timezone, :is_allday,
      :is_draft, :is_wheelchair_accessible, :is_adults_only, :is_tentative, :is_cancelled, :is_featured,
      :title, :description, :content,
      :organizer, :organizer_url,
      :location, :address, :city, :province, :country, :location_url,
      :external_links_attributes, :edit_comment, :tag_list
    )
  end
end

app/views/events/_event.ics.erb
# encoding: utf-8 <%
%>BEGIN:VEVENT<%= "\r\n"
# old UID was: "#{event.id}-event@wayground.ca". Changed because Versions reset, putting SEQUENCE out of sync
%>UID:<%= event.id %>.event@wayground.ca<%= "\r\n"
%>CREATED:<%= event.created_at.utc.to_s(:icalendar_utc) %><%= "\r\n"
%>DTSTAMP:<%= event.updated_at.utc.to_s(:icalendar_utc) %><%= "\r\n"
# special case the start and end date when it’s an all-day event (no time, just dates)
%>DTSTART<%= event.is_allday? ? ":#{event.start_at.to_s(:icalendar_date)}" : event.start_at.icalendar_with_zone %><%= "\r\n"
%><% if event.end_at?
  # If it’s an all day event, we put the end date as the day after it’s over,
  # because that's just how iCalendar rolls...
  %>DTEND<%= event.is_allday? ? ":#{event.end_at.advance(days: 1).to_s(:icalendar_date)}" : event.end_at.icalendar_with_zone %><%= "\r\n"
%><% end
%>SUMMARY:<%= event.title.icalendar_encoding.fold!(75,8).html_safe %><%= "\r\n"
%><% if event.description?
  %>DESCRIPTION:<%= event.description.icalendar_encoding.fold!(75,12).html_safe %><%= "\r\n"
%><% end
%>CLASS:PUBLIC<%= "\r\n"
%>URL:<%= event_url(event).icalendar_encoding.fold!(75,4).html_safe %><%= "\r\n"
%><% if event.location? || event.address?
  # TODO: handle city, province, country, location_url.
  location = event.location + (event.address? ? " (#{event.address})" : '')
  %>LOCATION:<%= location.icalendar_encoding.fold!(75,9).html_safe %><%= "\r\n"
%><% end
%>STATUS:<%
if event.is_tentative? || !(event.is_approved?)
  %>TENTATIVE<%
elsif event.is_cancelled?
  %>CANCELLED<%
else
  %>CONFIRMED<%
end %><%= "\r\n"
%><%
if event.organizer?
  organizer = ";CN=#{event.organizer.icalendar_encoding.gsub(':', '-')}:"
  if event.organizer_url?
    organizer += event.organizer_url.icalendar_encoding
  end
  %>ORGANIZER<%= organizer.fold!(75,9).html_safe %><%= "\r\n"
%><%
elsif event.organizer_url?
  %>ORGANIZER:<%= event.organizer_url.fold!(75,10).html_safe %><%= "\r\n"
%><%
end

#if event.external_links.count > 0
#  event.external_links.each do |el|
#    % >ATTACH:< %= el.url.icalendar_encoding.fold!(75,7) % >
#< %
#  end
#end
%>SEQUENCE:<%= event.versions.count %><%= "\r\n"
%><%

# TODO: more icalendar fields
#
#CATEGORIES: = event.tags.join(',').upcase.fold!(75,11)

%>END:VEVENT<%= "\r\n"
%>

app/views/events/delete.html.erb
<h1>Delete “<%= link_to @event.title, @event %>” Event?</h1>

<%= form_tag(@event, method: :delete) do %>
<p><%= submit_tag "Delete Event" %></p>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event “<%= link_to @event.title, @event %>”</h1>

<%= render 'form', { event: @event } %>

app/views/events/index.html.erb
<%
content_for(:head) do
  %><link rel="alternate" href="<%= events_path(format: 'ics') %>" type="text/calendar" title="icalendar file for events" />
<link rel="profile" href="http://microformats.org/profile/hcalendar" />
<%
end
main_section_class 'event-list'

%><h2><%= page_metadata.title %></h2>
<%
if @tag.present? && @range != 'all'
  %><p><%= link_to "Include past events tagged “#{@tag}”", events_path(r: 'all', tag: @tag), class: 'action' %></p>
<%
end -%>
<p><%= link_to 'Subscribe to this calendar in your calendar application',
  "webcal://#{request.host_with_port}#{events_path(format: :ics, r: params[:r])}", class: 'ics',
  title: 'Calendar subscription link, compatible with most calendar applications' %>.</p>
<%= #show_pagination_header('events')
-%>
<%= #show_pagination_selector
-%>
<%= render 'events', { events: @events, user: @user } %>
<%

add_submenu_item(title: 'Upcoming Events', path: events_path, attrs: { class: 'list' })
add_submenu_item(title: 'Past Events', path: events_path(r: 'past'), attrs: { class: 'list' })
add_submenu_item(title: 'All Events', path: events_path(r: 'all'), attrs: { class: 'list' })
add_submenu_item(title: 'Calendar View', path: calendar_path, attrs: { class: 'cal' })
add_submenu_item(title: 'Calendar Subscription Options',
  path: calendar_subscribe_path, attrs: { class: 'subscribe' }
)

if @user && @user.authority_for_area(Event.authority_area, :can_create)
  add_submenu_item(title: 'New Event', path: new_event_path, attrs: { class: 'new' })
end
-%>

app/views/events/index.txt.erb
<%= Wayground::Application::NAME %>
Events List
http://<%= request.host_with_port %>/

<%

date_idx = nil
@events.each do |event|
  unless event.is_cancelled?
    event_start = event.start_at
    event_end = event.end_at
    event_date = event_start.to_date
    multi_day = event_end && (event_end.to_date > event_date)
    if date_idx != event_date
      date_idx = event_date
      date_hdr = event_start.to_s(:plain_date)
      %><%= '_' * date_hdr.size %>
<%= date_hdr %>

<%
    end
    if event.is_allday
      if multi_day
        # event spans more than one day
        # TODO: change date to_s call to reflect untimed day
        %>until <%= event_end.to_s(:plain_date) %>:
<%    else
        %>All day:
<%    end
    else
      %><%= event_start.to_s(:plain_time).strip %><%
      unless event_end.blank?
        if multi_day
          %> to <%= event_end.to_s(:plain_datetime) %><%
        else
          %>—<%= event_end.to_s(:plain_time).strip %><%
        end
      end %>:
<%
    end


    %><%= event.title.html_safe %>
<%

    event_location = event.location
    event_address = event.address? ? event.address : nil
    # modify the address to include the city, province, country - if they aren’t the defaults
    event_city = event.city? ? event.city : nil
    event_province = event.province? ? event.province : nil
    event_country = event.country? ? event.country : nil
    if event.country == Wayground::Application::DEFAULT_COUNTRY
      event_country = nil
      if event.province == Wayground::Application::DEFAULT_PROVINCE
        event_province = nil
        if event.city == Wayground::Application::DEFAULT_CITY
          event_city = nil
        end
      end
    end
    if event_city
      event_address = [event_address, event_city, event_province, event_country].compact.join(', ')
    end

    if event_location.present?
      %>  <%= event.location.html_safe %><%
      if event_address.present?
        %> (<%= event_address.html_safe %>)<%
      end
      %>
<%  elsif event_address.present?
      %>  <%= event_address.html_safe %>
<%  end


    if event.description?
      # compress linebreaks and insert double space at beginning of each line
      %><%= event.description.gsub(/[\r\n]+/, "\n").gsub(/^/, '  ').html_safe %>
<%
    end


    event_organizer = event.organizer
    if event_organizer.present?
      %>  Presented by <%= event_organizer.html_safe %>.
<%  end

%>
  <%= event_url(event).html_safe %>

<%
  end
end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', { event: @event } %>

app/views/events/show.html.erb
<%
require 'event_presenter'

event ||= @event
@versioned_item = event # let the application template know we’re looking at an item with versions
main_section_class 'vevent'

presenter = EventPresenter.new(view: self, event: event, user: @user)

content_for(:head) do
  %><link rel="alternate" href="<%= event_path(event, format: 'ics') %>" type="text/calendar" title="icalendar file for event" />
<link rel="profile" href="http://microformats.org/profile/hcalendar" />
<%
end

attrs = presenter.event_heading_attrs
attrs[:class] ||= []
attrs[:class] << 'summary'
%><%= presenter.html_tag(:h2, attrs) { presenter.present_status + event.title } %>

<p><%= presenter.present_schedule_with_date %>
<br /><%= link_to 'Download to your calendar.', event_path(event, format: 'ics'), class: 'ics', title: "Download this event as a file compatible with most calendar applications" %></p>

<%= presenter.present_location_block %>
<%
organizer = presenter.present_organizer
if organizer.present?
  %><p><%= organizer %></p>

<%
end

if event.description?
  %><%= simple_text_to_html(event.description) %>

<%
end

if event.content?
  %><%= simple_text_to_html(event.content) %>

<%
end


if event.external_links.count > 0
  content_for(:other_sections) do
    %>
<section class="external_links"><h3>Links for this event</h3>
<ul>
<%
  event.external_links.each do |external_link|
    %><%= render 'external_links/external_link', { user: @user, item: event, external_link: external_link } %><%
  end
%></ul>
</section>
<%
  end
end

user_can_update_this_event = @user && event.authority_for_user_to?(@user, :can_update)
if event.tags.count > 0 || user_can_update_this_event
  content_for(:other_sections) do
    %>
<section class="tags"><h3>Tags</h3>
<ul>
<%
  event.tags.each do |tag|
    %><li><%= link_to tag.title, events_path(tag: tag.tag), { rel: 'tag' } %></li>
<%
  end
%></ul>
<%
if user_can_update_this_event
  existing_tags = event.tag_list.to_s
  %><%= form_tag(update_tags_event_url(event)) do %>
<p><%= text_field_tag :tag_list, existing_tags %>
<br /><%= submit_tag "Update Tags" %></p>
<% end %><%
end
%></section>
<%
  end
end


if @user
  if event.authority_for_user_to?(@user, :can_update)
    add_submenu_item(title: 'Edit', path: edit_event_path(event), attrs: { class: 'edit' })
  end
  if !(event.is_approved?) && event.authority_for_user_to?(@user, :can_approve)
    add_submenu_item(title: 'Approve', path: approve_event_path(event),
      attrs: {
        class: 'approve',
        data: { confirm: "Are you sure you want to approve the event “#{event.title}”?" },
        method: :post
      }
    )
  end
  if event.authority_for_user_to?(@user, :can_delete)
    if event.authority_for_user_to?(@user, :can_update)
      add_submenu_item(title: 'Merge', path: merge_event_path(event),
        attrs: { class: 'merge', title: 'Merge with another existing Event' }
      )
    end
    add_submenu_item(title: 'Delete', path: [:delete, event],
      attrs: { class: 'delete', data: { confirm: 'Are you sure?' }, method: :delete }
    )
  end
  if event.authority_for_user_to?(@user, :can_create)
    add_submenu_item(title: 'Add External Link', path: new_event_external_link_path(event),
      attrs: { class: 'new' }
    )
  end
end

date = event.start_at
add_submenu_item(title: 'Calendar View', path: calendar_month_path(date.year, date.strftime('%m')), attrs: { class: 'cal' })
add_submenu_item(title: 'Events List View', path: events_path, attrs: { class: 'list' })
add_submenu_item(title: 'Calendar Subscription Options',
  path: calendar_subscribe_path, attrs: { class: 'subscribe' }
)

if @user && @user.authority_for_area(Event.authority_area, :can_create)
  add_submenu_item(title: 'New Event', path: new_event_path, attrs: { class: 'new' })
end
-%>