config/routes.rb
Rails.application.routes.draw do
  concern :versioned do
    resources :versions, except: %i[new create edit update destroy]
  end

  root to: 'paths#sitepath', via: :get, url: '/'

  # USERS
  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create'
  get 'account/confirm/:confirmation_code' => 'users#confirm', as: :confirm_account
  resource :account, controller: 'users', except: %i[index new create destroy]
  get 'profile/:id' => 'users#profile', as: :profile
  # SESSIONS
  get 'signin' => 'sessions#new', as: :signin
  post 'signin' => 'sessions#create'
  get 'signout' => 'sessions#delete', as: :signout
  delete 'signout' => 'sessions#destroy'
  # OAUTH
  match 'auth/:provider/callback' => 'sessions#oauth_callback', via: %i[get post]
  # AUTHORITIES
  resources :authorities
  # SETTINGS
  resources :settings do
    collection { get 'initialize_defaults' }
  end

  # CONTENT
  resources :paths
  resources :pages, concerns: :versioned
  resources :documents
  get 'download/:id/*filename' => 'documents#download', as: :download
  resources :events, concerns: :versioned do
    member do
      get 'approve'
      post 'approve' => 'events#set_approved'
      get 'merge'
      post 'merge' => 'events#perform_merge'
      post 'update_tags'
    end
    resources :external_links
  end
  resources :images
  resources :sources do
    member do
      get 'processor'
      post 'processor' => 'sources#runprocessor'
    end
  end
  get 'tags' => 'tags#index'
  get 'tags/:tag' => 'tags#tag'

  # PROJECTS
  resources :projects
  get 'project/*projecturl' => 'projects#show', as: :project_name, format: false

  # Calendar
  month_regexp = /0[1-9]|1[0-2]/
  year_regexp = /\d{4}/
  get 'calendar' => 'calendar#index', as: :calendar
  get 'calendar/subscribe' => 'calendar#subscribe', as: :calendar_subscribe
  get 'calendar/:year/:month/:day' => 'calendar#day', as: :calendar_day,
      constraints: { year: year_regexp, month: month_regexp, day: /0[1-9]|[1-3]\d/ }
  get 'calendar/:year/:month' => 'calendar#month', as: :calendar_month,
      constraints: { year: year_regexp, month: month_regexp }
  get 'calendar/:year' => 'calendar#year', as: :calendar_year,
      constraints: { year: year_regexp }

  get '*url' => 'paths#sitepath', format: false
end

app/models/setting.rb
# System-wide settings.
class Setting < ApplicationRecord
  acts_as_authority_controlled authority_area: 'Admin', item_authority_flag_field: :always_private

  validates :key, presence: true

  default_scope { order('key') }

  # Key-indexed accessor for the values of settings.
  def self.[](key)
    setting = find_by(key: key)
    setting ? setting.value : nil
  end

  # Key-indexed assignment for the values of settings.
  def self.[]=(key, value)
    setting = find_by(key: key)
    # create the setting if it doesn’t already exist
    setting ||= new(key: key)
    setting.value = value.to_s
    setting.save!
  end

  # Key-indexed removal of settings.
  def self.destroy(key)
    setting = find_by(key: key)
    setting&.destroy
  end

  # Set the values of settings, but don’t overwrite existing values if present.
  def self.assign_missing_with_defaults(key_value_pairs)
    key_value_pairs.each do |key, value|
      # if the setting has not been set yet, use the value provided
      self[key] ||= value.to_s
    end
  end
end

app/controllers/settings_controller.rb
# Administer site-wide Settings.
class SettingsController < ApplicationController
  before_action :set_setting, except: %i[initialize_defaults index new create]
  before_action :requires_view_authority, only: %i[index show]
  before_action :requires_create_authority, only: %i[initialize_defaults new create]
  before_action :requires_update_authority, only: %i[edit update]
  before_action :requires_delete_authority, only: %i[delete destroy]
  before_action :set_section
  before_action :set_new_setting, only: %i[new create]

  # Setup default Settings for the system as a whole.
  # Currently, just the global_start_date.
  def initialize_defaults
    Setting.assign_missing_with_defaults(
      { global_start_date: Time.zone.now.to_date }.merge((params[:settings] || {}))
    )
    flash.notice = 'Settings have been initialized to defaults (where not already set).'
    redirect_to settings_url
  end

  # GET /settings
  # GET /settings.xml
  def index
    @settings = Setting.all
    page_metadata(title: 'Settings')
  end

  # GET /settings/1
  # GET /settings/1.xml
  def show
    page_metadata(title: "Setting: #{@setting.key}")
  end

  # GET /settings/new
  # GET /settings/new.xml
  def new; end

  # POST /settings
  # POST /settings.xml
  def create
    if @setting.save
      redirect_to(@setting, notice: 'Setting was successfully created.')
    else
      render action: 'new'
    end
  end

  # GET /settings/1/edit
  def edit
    page_metadata(title: "Edit Setting: #{@setting.key}")
  end

  # PUT /settings/1
  # PUT /settings/1.xml
  def update
    if @setting.update(setting_params)
      redirect_to(@setting, notice: 'Setting was successfully updated.')
    else
      page_metadata(title: "Edit Setting: #{@setting.key}")
      render action: 'edit'
    end
  end

  # GET /settings/1/delete
  def delete
    page_metadata(title: "Delete Setting: #{@setting.key}")
  end

  # DELETE /settings/1
  # DELETE /settings/1.xml
  def destroy
    @setting.destroy
    redirect_to(settings_url, notice: "The setting for “#{@setting.key}” has been removed.")
  end

  protected

  # Most of the actions for this controller receive the id of a Setting as a parameter.
  def set_setting
    @setting = Setting.find(params[:id])
  end

  def requires_authority(action)
    user = current_user
    setting_allowed = @setting && @setting.authority_for_user_to?(user, action)
    can_do = setting_allowed || (user && user.authority_for_area(Setting.authority_area, action))
    raise Wayground::AccessDenied unless can_do
  end

  def requires_view_authority
    requires_authority(:can_view)
  end

  def requires_create_authority
    requires_authority(:can_create)
  end

  def requires_update_authority
    requires_authority(:can_update)
  end

  def requires_delete_authority
    requires_authority(:can_delete)
  end

  def set_section
    @site_section = :settings
  end

  def set_new_setting
    page_metadata(title: 'New Setting')
    @setting = Setting.new(setting_params)
  end

  def setting_params
    params.fetch(:setting, {}).permit(:key, :value)
  end
end

app/views/settings/_form.html.erb
<%= form_for(setting) do |f| %>
<%= show_errors(setting) %>
<table><tbody>
<tr><th><%= f.label :key %></th>
  <td><%= f.text_field :key, size: 32, maxlength: 255 %></td></tr>
<tr><th><%= f.label :value %></th>
  <td><%= f.text_area :value, rows: 8 %></td></tr>
</tbody>
<tfoot><tr><th></th><td class="actions"><%= f.submit('Save Setting') %></td></tr></tfoot>
</table>
<% end -%>

app/views/settings/delete.html.erb
<h1>Delete Setting “<%= link_to @setting.title, @setting %>”?</h1>

<%= form_tag(@setting, method: :delete) do %>
<p><%= submit_tag "Delete Setting" %></p>
<% end %>

app/views/settings/edit.html.erb
<h1>Update Setting “<%= @setting.key %>”</h1>

<%= render 'form', { setting: @setting } %>

app/views/settings/index.html.erb
<h1>Settings</h1>
<p class="actions">
<%= link_to 'Add New Setting', new_setting_path, class: 'action' %>
<%= link_to 'Initialize Default Settings', initialize_defaults_settings_path, class: 'action' %>
</p>
<% if @settings.count > 0 %>
<table><tbody>
<% @settings.each do |setting|
  %><tr><th><%= setting.key %>:</th> <td><%= setting.value %></td> <td><%= link_to 'Edit', edit_setting_path(setting), class: 'action' %><%= separator %> <%= link_to 'Delete', delete_setting_path(setting), class: 'action' %></td></tr>
<% end -%>
</tbody></table>
<% else %>
<p><strong>No settings available.</strong></p>
<% end -%>

app/views/settings/new.html.erb
<h1>Add a Setting</h1>

<%= render 'form', { setting: @setting } %>

app/views/settings/show.html.erb
<h1>Setting: <%= @setting.key %></h1>
<table><tbody>
<tr><th>Value:</th> <td><%= @setting.value %></td></tr>
</tbody></table>

<p class="actions">
<%= link_to 'Edit', edit_setting_path(@setting), class: 'action' %>
<%= link_to 'Delete', delete_setting_path(@setting), class: 'action' %>
</p>