config/routes.rb
Rails.application.routes.draw do
  concern :versioned do
    resources :versions, except: %i[new create edit update destroy]
  end

  root to: 'paths#sitepath', via: :get, url: '/'

  # USERS
  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create'
  get 'account/confirm/:confirmation_code' => 'users#confirm', as: :confirm_account
  resource :account, controller: 'users', except: %i[index new create destroy]
  get 'profile/:id' => 'users#profile', as: :profile
  # SESSIONS
  get 'signin' => 'sessions#new', as: :signin
  post 'signin' => 'sessions#create'
  get 'signout' => 'sessions#delete', as: :signout
  delete 'signout' => 'sessions#destroy'
  # OAUTH
  match 'auth/:provider/callback' => 'sessions#oauth_callback', via: %i[get post]
  # AUTHORITIES
  resources :authorities
  # SETTINGS
  resources :settings do
    collection { get 'initialize_defaults' }
  end

  # CONTENT
  resources :paths
  resources :pages, concerns: :versioned
  resources :documents
  get 'download/:id/*filename' => 'documents#download', as: :download
  resources :events, concerns: :versioned do
    member do
      get 'approve'
      post 'approve' => 'events#set_approved'
      get 'merge'
      post 'merge' => 'events#perform_merge'
      post 'update_tags'
    end
    resources :external_links
  end
  resources :images
  resources :sources do
    member do
      get 'processor'
      post 'processor' => 'sources#runprocessor'
    end
  end
  get 'tags' => 'tags#index'
  get 'tags/:tag' => 'tags#tag'

  # PROJECTS
  resources :projects
  get 'project/*projecturl' => 'projects#show', as: :project_name, format: false

  # Calendar
  month_regexp = /0[1-9]|1[0-2]/
  year_regexp = /\d{4}/
  get 'calendar' => 'calendar#index', as: :calendar
  get 'calendar/subscribe' => 'calendar#subscribe', as: :calendar_subscribe
  get 'calendar/:year/:month/:day' => 'calendar#day', as: :calendar_day,
      constraints: { year: year_regexp, month: month_regexp, day: /0[1-9]|[1-3]\d/ }
  get 'calendar/:year/:month' => 'calendar#month', as: :calendar_month,
      constraints: { year: year_regexp, month: month_regexp }
  get 'calendar/:year' => 'calendar#year', as: :calendar_year,
      constraints: { year: year_regexp }

  get '*url' => 'paths#sitepath', format: false
end

app/models/document.rb
# Metadata for a data file. (The actual file data is kept in Datastore.)
class Document < ApplicationRecord
  acts_as_authority_controlled authority_area: 'Content'

  # the actual data of the file is stored in a separate table
  belongs_to :datastore
  # The user who uploaded the document. May be nil if the system generated the document.
  belongs_to :user
  # The optional Path that contains this document.
  belongs_to :container_path, class_name: 'Path'
  # The Path object that lets the document be accessed via a sitepath (such as “/somestuff/filename”).
  # Will be nil if the document does not have a container_path.
  has_one :path, as: :item, validate: true, dependent: :destroy

  before_save :determine_size
  before_save :generate_path
  before_update :update_path

  # TODO: create a validator class for filenames with extensions
  validates(
    :filename,
    length: { within: 1..127 },
    format: {
      with: %r{\A(/|([\w_~\+\-]+)(\.[\w_]+)?/?)\z},
      message:
        'must only be letters, numbers, dashes and underscores, with an optional extension;' \
        ' e.g., “a-filename_1.txt”'
    }
  )
  validates(
    :content_type,
    presence: true,
    format: { with: %r{\A[a-z\-]+/[a-z\+\-]+\z}, message: 'is not a valid content type' }
  )
  # require data to be set, but allow it to be empty
  validates :datastore, presence: { unless: proc { |doc| doc.data == '' } }

  # TODO: genericize the for_user scope so it can come from the authority_controlled library instead
  scope :for_user, lambda { |user|
    if user.nil?
      # if anonymous user, don’t allow any authority controlled documents
      where(is_authority_controlled: false)
    elsif user.authority_for_area(authority_area)
      # if user has admin view authority on the Content area, allow all documents
    else
      # need to check if user has authority for non-public documents
      # allow non-authority controlled documents, and documents the user has authority for
      joins(
        sanitize_sql_array(
          [
            # check against the authorities table
            'LEFT OUTER JOIN authorities ' +
            # match the authorities for the documents
            "ON authorities.item_type = 'Document' AND authorities.item_id = documents.id " +
            # match authorities for the specified user
            'AND authorities.user_id = ?',
            user.id
          ]
        )
      )
        .where(
          [
            # show public, not authority-controlled, documents
            'documents.is_authority_controlled = ? ' +
            # and documents posted by the user
            'OR documents.user_id = ? ' +
            # and documents that have an appropriate matching authority for the user
            'OR (authorities.is_owner = ? OR authorities.can_view = ?)',
            false, user.id, true, true
          ]
        )
    end
  }

  def determine_size
    self.size = (data ? data.size : 0)
  end

  def generate_path(sitepath = nil)
    if container_path.present? && !path
      self.path = Path.new(sitepath: (sitepath || calculate_sitepath))
      path.item = self
    end
  end

  def update_path
    sitepath = calculate_sitepath
    if !sitepath
      if path
        path.destroy
        self.path = nil
      end
    elsif path
      path.update!(sitepath: sitepath)
    else
      generate_path(sitepath)
      path.save!
    end
  end

  def calculate_sitepath
    "#{container_path.sitepath}/#{filename}".gsub(%r{//+}, '/') if container_path
  end

  delegate :sitepath, to: :path, allow_nil: true

  def file=(file)
    return if file.blank? || file.is_a?(String)
    if filename.blank?
      self.filename =
        begin
          file.original_filename
        rescue
          file.path.match(%r{([^/]+)\z})[1]
        end
      cleanup_filename
    end
    if content_type.blank?
      self.content_type =
        begin
          file.content_type
        rescue
          'application/data'
        end
    end
    self.data = file.read
  end

  # Replaces or removes any disallowed characters from the filename.
  def cleanup_filename
    # Convert spaces to underscores,
    filename.gsub!(/ +/, '_')
    # em and en dashes to plain dashes,
    filename.gsub!(/[–—]/, '-')
    # convert accented characters to ascii equivalents,
    filename.gsub!(/[ªáÁàÀâÂåÅäÄãÃ]/, 'a')
    filename.gsub!(/[èéëêÈÉËÊ]/, 'e')
    filename.gsub!(/[ìíïîÌÍÏÎ]/, 'i')
    filename.gsub!(/[òóöôõÒÓÖÔÕøØº]/, 'o')
    filename.gsub!(/[ùúüûÙÚÛµ]/, 'u')
    filename.gsub!(/[æÆ]/, 'ae')
    filename.gsub!(/[œŒ]/, 'oe')
    filename.gsub!(/[ç¢]/, 'c')
    filename.gsub!(/[ƒ]/, 'f')
    filename.gsub!(/[ﬁ]/, 'fi')
    filename.gsub!(/[ﬂ]/, 'fl')
    filename.gsub!(/[ñÑ]/, 'n')
    # and then remove all forbidden characters.
    filename.gsub!(/[^A-Za-z0-9_\.\-]+/, '')
  end

  def custom_filename=(custom)
    self.filename = custom if custom.present?
  end

  def custom_filename
    nil
  end

  delegate :data, to: :datastore, allow_nil: true

  def data=(data)
    self.datastore ||= Datastore.new
    self.datastore.data = data
  end

  # Set the response headers for when this document is to be the content/body of the HTTP response.
  def assign_headers(response)
    # Content-Length is auto-set
    response.headers.merge!(
      'Last-Modified' => (updated_at || created_at).utc.to_s(:http_header),
      'Content-Type' => content_type
    )
    # set Cache-control to “private/public, max-age=?, no-transform” where max-age is in seconds
    cache_params =
      if authority_restricted?
        { max_age: 30.minutes, public: false }
      else
        { max_age: 1.day, public: true }
      end
    response.cache_control.merge!(cache_params.merge!(extras: ['no-transform']))
  end
end

app/controllers/documents_controller.rb
# Access Documents.
class DocumentsController < ApplicationController
  before_action :set_document, except: %i[index new create]
  before_action :requires_view_authority, only: %i[download show]
  before_action :requires_create_authority, only: %i[new create]
  before_action :requires_update_authority, only: %i[edit update]
  before_action :requires_delete_authority, only: %i[delete destroy]
  before_action :set_section

  def download
    @document.assign_headers(response)
    render body: @document.data
  end

  def index
    @documents = paginate(Document.for_user(current_user))
    page_metadata(title: 'Documents Index')
  end

  def show
    page_metadata(title: "Document “#{@document.filename}”", description: @document.description)
  end

  def new
    @document = Document.new
    page_metadata(title: 'New Document')
  end

  def create
    @document = Document.new(document_params)
    @document.user = current_user

    if @document.save
      redirect_to(@document, notice: 'Document was successfully created.')
    else
      page_metadata(title: 'New Document')
      render action: 'new'
    end
  end

  def edit
    page_metadata(title: "Edit Document #{@document.filename}")
  end

  def update
    if @document.update(document_params)
      redirect_to(@document, notice: 'Document was successfully updated.')
    else
      page_metadata(title: "Edit Document #{@document.filename}")
      render action: 'edit'
    end
  end

  def delete
    page_metadata(title: "Delete Document #{@document.filename}")
  end

  def destroy
    @document.destroy
    redirect_to(documents_url)
  end

  protected

  # The actions for this controller, other than viewing, require authorization.
  def requires_authority(action)
    user = current_user
    document_allowed = @document && @document.authority_for_user_to?(user, action)
    can_do = document_allowed || (user && user.authority_for_area(Document.authority_area, action))
    raise Wayground::AccessDenied unless can_do
  end

  def requires_view_authority
    requires_authority(:can_view)
  end

  def requires_create_authority
    requires_authority(:can_create)
  end

  def requires_update_authority
    requires_authority(:can_update)
  end

  def requires_delete_authority
    requires_authority(:can_delete)
  end

  # Most of the actions for this controller receive the id of an Authority as a parameter.
  def set_document
    @document = Document.find(params[:id])
  end

  def set_section
    @site_section = :documents
  end

  def document_params
    params.fetch(:document, {}).permit(:file, :custom_filename, :description, :is_authority_controlled, :data)
  end
end

app/views/documents/_form.html.erb
<%= form_for(@document, html: { multipart: true }) do |f| %>
<%= show_errors(@document) %>
<table><tbody>
<% if @document.new_record? -%>
<tr><th><%= f.label :file %></th>
  <td><%= f.file_field :file %></td></tr>
<% end -%>
<tr><th><%= f.label :custom_filename %></th>
  <td><%= f.text_field :custom_filename %>
  <br />You can override the filename for the document here.
  <br />You may want to do that to ensure it is a usable name.
  <br />It must be only letters, numbers, dashes and underscores, with an optional extension (e.g., “.txt”).
  <br />Note that it must not contain spaces, accented characters or other punctuation.</td></tr>
<tr><th><%= f.label :description %></th>
  <td><%= f.text_field :description, size: 72 %></td></tr>
</tbody>
<tfoot><tr><th></th><td><%= f.submit 'Save Document' %></td></tr></tfoot>
</table>
<% end %>

app/views/documents/delete.html.erb
<h1>Delete Document “<%= @document.filename %>”?</h1>

<%= form_tag(delete_document_path(@document), method: :delete) do %>
<p><%= submit_tag "Delete Document" %></p>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

app/views/documents/index.html.erb
<h1>Documents</h1>
<%= show_pagination_header('documents') %>
<%= show_pagination_selector %>
<table>
<% @documents.each do |document|
  %><tr class="document_item"><td><%= icon_for_content_type(document.content_type) %><%= document.filename %> (<%= document.size %> bytes)
<%
  if document.description?
    %><br /><%= document.description %>
<% end
%></td><td><%= link_to 'Download', "/download/#{document.id}/#{document.filename}", class: 'action' %>
<%= link_to 'Details', document, class: 'action' %>
<%= link_to 'Edit', edit_document_path(document), class: 'action' %>
<%= link_to 'Delete', [:delete, document], data: { confirm: 'Are you sure?' }, method: :delete, class: 'action' %></td></tr>
<% end -%>
</table>

<p class="actions"><%= link_to 'New Document', new_document_path, class: 'action' %></p>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

app/views/documents/show.html.erb
<% user = @document.user
if user -%>
<p>
  <b>User:</b>
  <%= user.name %>
</p>
<% end
path = @document.path
if path -%>
<p>
  <b>Path:</b>
  <%= path.sitepath %>
</p>
<% end -%>
<p>
  <b>Filename:</b>
  <%= @document.filename %>
</p>

<p>
  <b>Size:</b>
  <%= @document.size %>
</p>

<p>
  <b>Content type:</b>
  <%= @document.content_type %>
</p>

<p>
  <b>Description:</b>
  <%= @document.description %>
</p>

<p class="actions"><%= link_to 'Download', "/download/#{@document.id}/#{@document.filename}", class: 'action' %>
<%= link_to 'Edit', edit_document_path(@document), class: 'action' %>
<%= link_to 'Delete', [:delete, @document], data: { confirm: 'Are you sure?' }, method: :delete, class: 'action' %>
<%= link_to 'New Document', new_document_path, class: 'action' %></p>