config/routes.rb
Rails.application.routes.draw do
  concern :versioned do
    resources :versions, except: %i[new create edit update destroy]
  end

  root to: 'paths#sitepath', via: :get, url: '/'

  # USERS
  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create'
  get 'account/confirm/:confirmation_code' => 'users#confirm', as: :confirm_account
  resource :account, controller: 'users', except: %i[index new create destroy]
  get 'profile/:id' => 'users#profile', as: :profile
  # SESSIONS
  get 'signin' => 'sessions#new', as: :signin
  post 'signin' => 'sessions#create'
  get 'signout' => 'sessions#delete', as: :signout
  delete 'signout' => 'sessions#destroy'
  # OAUTH
  match 'auth/:provider/callback' => 'sessions#oauth_callback', via: %i[get post]
  # AUTHORITIES
  resources :authorities
  # SETTINGS
  resources :settings do
    collection { get 'initialize_defaults' }
  end

  # CONTENT
  resources :paths
  resources :pages, concerns: :versioned
  resources :documents
  get 'download/:id/*filename' => 'documents#download', as: :download
  resources :events, concerns: :versioned do
    member do
      get 'approve'
      post 'approve' => 'events#set_approved'
      get 'merge'
      post 'merge' => 'events#perform_merge'
      post 'update_tags'
    end
    resources :external_links
  end
  resources :images
  resources :sources do
    member do
      get 'processor'
      post 'processor' => 'sources#runprocessor'
    end
  end
  get 'tags' => 'tags#index'
  get 'tags/:tag' => 'tags#tag'

  # PROJECTS
  resources :projects
  get 'project/*projecturl' => 'projects#show', as: :project_name, format: false

  # Calendar
  month_regexp = /0[1-9]|1[0-2]/
  year_regexp = /\d{4}/
  get 'calendar' => 'calendar#index', as: :calendar
  get 'calendar/subscribe' => 'calendar#subscribe', as: :calendar_subscribe
  get 'calendar/:year/:month/:day' => 'calendar#day', as: :calendar_day,
      constraints: { year: year_regexp, month: month_regexp, day: /0[1-9]|[1-3]\d/ }
  get 'calendar/:year/:month' => 'calendar#month', as: :calendar_month,
      constraints: { year: year_regexp, month: month_regexp }
  get 'calendar/:year' => 'calendar#year', as: :calendar_year,
      constraints: { year: year_regexp }

  get '*url' => 'paths#sitepath', format: false
end

app/models/authority.rb
require 'user'

# Gives authority to a user, on a given item or area, for performing specific actions.
class Authority < ApplicationRecord
  belongs_to :user
  belongs_to :authorized_by, class_name: 'User'
  belongs_to :item, polymorphic: true

  validates :user, presence: true
  # validates(area:, inclusion: { in: %w(global User Authority Page Event),
  #   allow_nil: true, allow_blank: true,
  #   message: "{{value}} is not a recognized area" })
  validates :area, presence: { if: proc { |authority| authority.item_type.blank? } }
  validates :item_id, presence: { if: proc { |authority| authority.item_type.present? } }

  scope :for_area, ->(area) { where(area: area) }
  scope :for_area_or_global, lambda { |area|
    where("(authorities.area = ? OR authorities.area = 'global')", area)
  }
  scope :for_item, ->(item) { where(item_id: item.id, item_type: item.class.name) }
  scope :for_item_or_area, lambda { |item|
    where(
      '((authorities.item_id = ? AND authorities.item_type = ?)' \
      " OR authorities.area = ? OR authorities.area = 'global')",
      item.id, item.class.name, item.authority_area
    )
  }
  scope :for_user, ->(user) { where(user_id: user.id) }
  scope :for_action, lambda { |action|
    raise "invalid action “#{action}”" unless action.match?(/\A(can_[a-z]+|is_owner)\z/)
    where("(authorities.#{action} = ? OR authorities.is_owner = ?)", true, true)
  }
  scope :where_owner, -> { where(is_owner: true) }

  def self.build_from_params(params)
    authority_params = params[:authority_params] || {}
    user = User.from_string(authority_params[:user_proxy].to_s)
    authority = user ? user.authorizations.build(authority_params) : Authority.new(authority_params)
    authority.authorized_by = params[:authorized_by]
    authority
  end

  # Find an Authority that gives the +user+ permission to perform the +action_type+ on the +item+.
  # Prefers authority instances designating the +user+ as the owner of the +item+.
  # +action_type+:: an access_control action symbol. If +nil+, does not restrict by action.
  #   Default: +:can_view+
  def self.user_has_for_item(user, item, action_type = :can_view)
    user_authorizations = Authority.for_user(user).for_item_or_area(item)
    user_authorizations = user_authorizations.for_action(action_type) unless action_type.nil?
    authority_that_gives_permission(user_authorizations, item, action_type)
  end

  # From a list of authorities, try to find an authority that gives permission,
  # prioritizing an authority that identifies the user as the owner of the item
  def self.authority_that_gives_permission(user_authorizations, item, action_type)
    valid_authority = nil
    user_authorizations.each do |authority|
      if authority.is_owner? && authority.item == item
        valid_authority = authority
        break
      elsif (action_type.nil? || authority[action_type]) && authority.item == item
        # second priority is for authorities on the item
        valid_authority = authority
      elsif (action_type.nil? || authority[action_type]) || authority.is_owner?
        valid_authority ||= authority
      end
    end
    valid_authority
  end

  # Setting the user via a string value (e.g., either an email address or id) or a User instance.

  # Returns the user’s email address as a proxy string for the user, or +false+ if missing.
  def user_proxy
    user && user.email
  end

  # Assigns the +user+ based on a string or User instance.
  # If +item+ is blank, user is set to nil.
  # If +item+ is a string matching an user email, id, or name, sets the user.
  # If +item+ is a User instance, sets the user.
  def user_proxy=(item)
    self.user =
      if item.blank?
        nil
      elsif item.is_a? String
        User.from_string(item)
      else
        item
      end
  end

  # def user_has_for_area(user, area, action_type = :can_view)
  #   if action_type.nil?
  #     Authority.for_user(user).for_area(area)
  #   else
  #     Authority.for_user(user).for_area(item).for_action(action_type)
  #   end
  # end

  def action!(action_type)
    return if self[action_type]
    self[action_type] = true
    save!
  end

  # Merge this authority into another authority (must be for the same user).
  # The various permission fields are OR’d,
  # the destination authority is saved,
  # and then this authority is destroyed.
  def merge_into!(destination_authority)
    raise TypeError unless destination_authority.is_a? Authority
    raise Wayground::UserMismatch unless destination_authority.user == user
    merge_values(destination_authority)
    if destination_authority.save
      destroy
      true
    else
      false
    end
  end

  private

  def merge_values(destination_authority)
    destination_authority.is_owner ||= is_owner
    destination_authority.can_create ||= can_create
    destination_authority.can_view ||= can_view
    destination_authority.can_update ||= can_update
    destination_authority.can_delete ||= can_delete
    destination_authority.can_invite ||= can_invite
    destination_authority.can_permit ||= can_permit
    destination_authority.can_approve ||= can_approve
  end
end

app/controllers/authorities_controller.rb
# Set authorities (permissions / access-control) for users.
class AuthoritiesController < ApplicationController
  before_action :requires_view_authority, only: %i[index show]
  before_action :requires_create_authority, only: %i[new create]
  before_action :requires_update_authority, only: %i[edit update]
  before_action :requires_delete_authority, only: %i[delete destroy]
  before_action :set_authority, except: %i[index new create]
  before_action :set_site_location, except: [:index]

  # GET /authorities
  # GET /authorities.xml
  def index
    @authorities = paginate(Authority)
    page_metadata(title: 'Authorities')
  end

  # GET /authorities/1
  # GET /authorities/1.xml
  def show
    page_metadata(title: 'Authority')
  end

  # GET /authorities/new
  # GET /authorities/new.xml
  def new
    @authority = Authority.new
    page_metadata(title: 'New Authority')
  end

  # POST /authorities
  def create
    create_params = { authority_params: authority_params, authorized_by: current_user }
    @authority = Authority.build_from_params(create_params)
    @user = @authority.user
    page_metadata(title: 'New Authority')
    if @authority.save
      redirect_to(authority_url(@authority.to_param), notice: 'Authority was successfully created.')
    else
      render action: 'new'
    end
  end

  # GET /authorities/1/edit
  def edit
    page_metadata(title: 'Update Authority')
  end

  # PUT /authorities/1
  # PUT /authorities/1.xml
  def update
    @authority.authorized_by = current_user
    page_metadata(title: 'Update Authority')
    if @authority.update(authority_params)
      redirect_to(@authority, notice: 'Authority was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # GET /authorities/1/delete
  def delete
    page_metadata(title: 'Delete Authority')
  end

  # DELETE /authorities/1
  # DELETE /authorities/1.xml
  def destroy
    @authority.destroy
    redirect_to(authorities_url)
  end

  protected

  # Most of the actions for this controller receive the id of an Authority as a parameter.
  def set_authority
    @authority = Authority.find(params[:id])
  end

  # Breadcrumbs for actions on this controller start with the index page.
  def set_site_location
    @site_breadcrumbs = [{ text: 'Authorities', url: authorities_path }]
  end

  def requires_view_authority
    can_view = current_user && current_user.authority_for_area('Authority', :can_view)
    raise Wayground::AccessDenied unless can_view
  end

  def requires_create_authority
    can_create = current_user && current_user.authority_for_area('Authority', :can_create)
    raise Wayground::AccessDenied unless can_create
  end

  def requires_update_authority
    can_update = current_user && current_user.authority_for_area('Authority', :can_update)
    raise Wayground::AccessDenied unless can_update
  end

  def requires_delete_authority
    can_delete = current_user && current_user.authority_for_area('Authority', :can_delete)
    raise Wayground::AccessDenied unless can_delete
  end

  def authority_params
    params.fetch(:authority, {}).permit(
      :item_type, :item_id, :area, :is_owner, :can_create, :can_view, :can_update,
      :can_delete, :can_invite, :can_permit, :can_approve, :user_proxy
    )
  end
end

app/views/authorities/_form.html.erb
<%= form_for(@authority) do |f| %>
<%= show_errors(@authority) %>

<table>
<tbody>
<tr><th><%= f.label :user_proxy, 'User' %></th>
  <td><%= f.text_field :user_proxy %></td></tr>
<tr><th><%= f.label :item_type %></th>
  <td><%= f.text_field :item_type %></td></tr>
<tr><th><%= f.label :item_id %></th>
  <td><%= f.text_field :item_id %></td></tr>
<tr><th><%= f.label :area %></th>
  <td><%= f.text_field :area %></td></tr>
<tr><th></th><td><%= f.check_box :is_owner %><%= f.label :is_owner %></td></tr>
<tr><th></th><td><%= f.check_box :can_create %><%= f.label :can_create %></td></tr>
<tr><th></th><td><%= f.check_box :can_view %><%= f.label :can_view %></td></tr>
<tr><th></th><td><%= f.check_box :can_update %><%= f.label :can_update %></td></tr>
<tr><th></th><td><%= f.check_box :can_delete %><%= f.label :can_delete %></td></tr>
<tr><th></th><td><%= f.check_box :can_invite %><%= f.label :can_invite %></td></tr>
<tr><th></th><td><%= f.check_box :can_permit %><%= f.label :can_permit %></td></tr>
<tr><th></th><td><%= f.check_box :can_approve %><%= f.label :can_approve %></td></tr>
</tbody>
<tfoot><tr><th></th><td><%= f.submit 'Save Authority' %></td></tr></tfoot>
</table>
<% end -%>

app/views/authorities/delete.html.erb
<h1>Delete <%= @authority.area %> Authority for User “<%= @authority.user.name %>”</h1>

<%= form_tag(authority_path(@authority), method: :delete) do %>
<p><%= submit_tag "Delete Authority" %></p>
<% end %>

app/views/authorities/edit.html.erb
<h1>Editing authority</h1>

<%= render 'form' %>

app/views/authorities/index.html.erb
<h1>List of Authorities</h1>
<%= show_pagination_header('authorities') %>
<%= show_pagination_selector %>
<table>
<thead><tr>
<th>User</th>
<th>Item</th>
<th>Area</th>
<th>Is owner</th>
<th>Can create</th>
<th>Can view</th>
<th>Can update</th>
<th>Can delete</th>
<th>Can invite</th>
<th>Can permit</th>
<th>Can approve</th>
<th>Actions</th>
</tr></thead>
<tbody>
<% @authorities.each do |authority|
  %><tr>
<td><%= authority.user %></td>
<td><%= authority.item %></td>
<td><%= authority.area %></td>
<td><%= authority.is_owner %></td>
<td><%= authority.can_create %></td>
<td><%= authority.can_view %></td>
<td><%= authority.can_update %></td>
<td><%= authority.can_delete %></td>
<td><%= authority.can_invite %></td>
<td><%= authority.can_permit %></td>
<td><%= authority.can_approve %></td>
<td><%= link_to 'Show', authority %>
• <%= link_to 'Edit', edit_authority_path(authority) %>
• <%= link_to 'Delete', [:delete, authority], data: { confirm: 'Are you sure?' }, method: :delete %></td>
</tr>
<% end %></tbody>
</table>

<p><%= link_to 'New Authority', new_authority_path %></p>

app/views/authorities/login_required.html.erb
<%
page_metadata.title ||= 'Sign In Required'

%><h1>Sign In Required</h1>
<p>You need to <%= link_to "Sign In", signin_path %> before you can access the requested item.</p>

app/views/authorities/new.html.erb
<h1>New Authority</h1>

<%= render 'form' %>

app/views/authorities/show.html.erb
<% user = @authority.user -%>
<p><b>User:</b> <%= link_to user.email, profile_path(user) %></p>

<% item = @authority.item
if item
  %><p><b><%= item.class.name %>:</b> <%= item.name %></p>
<% end -%>

<p><b>Area:</b> <%= @authority.area %></p>

<p><b>Is owner:</b> <%= @authority.is_owner %></p>

<p>
<b>Can create:</b>
<%= @authority.can_create %>
<br /><b>Can view:</b>
<%= @authority.can_view %>
<br /><b>Can update:</b>
<%= @authority.can_update %>
<br /><b>Can delete:</b>
<%= @authority.can_delete %>
<br /><b>Can invite:</b>
<%= @authority.can_invite %>
<br /><b>Can permit:</b>
<%= @authority.can_permit %>
<br /><b>Can approve:</b>
<%= @authority.can_approve %>
</p>

<p class="actions"><%= link_to 'Edit', edit_authority_path(@authority), class: 'action' %></p>

app/views/authorities/unauthorized.html.erb
<%
page_metadata.title ||= '403 Forbidden'

%><h1>Restricted Access</h1>
<p>You do not have permission to access what you requested.</p>
<p><%
if current_user
  %>If you have an additional account (such as an administrator account), you may need to sign out from your current account and sign in to that account.<%
else
  %>You may need to <%= link_to "Sign In", signin_path %> in order to access the requested item.<%
end
%></p>